### ISSUE TITLE
Error while joining on the server

### ISSUE THREAD

**Issue by Dominiik001** [bluecreeper111/JEssentials#13]
`14:11:00] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to JEssentials v1.4.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot.jar:git-Spigot-4d24e36-5193f76]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.PlayerConnection.chat(PlayerConnection.java:1588) [spigot.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1526) [spigot.jar:git-Spigot-4d24e36-5193f76]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat$1.run(PacketPlayInChat.java:41) [spigot.jar:git-Spigot-4d24e36-5193f76]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_211]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NullPointerException
        at com.bluecreeper111.jessentials.event.playerChat.onPlayerChat(playerChat.java:43) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-4d24e36-5193f76]
        ... 11 more

**Comment by jeremy-carefoot** [comment]
This is simply because you don't have a permissions plugin for groups. I strongly advise you download one.
