### ISSUE TITLE
IDK

### ISSUE THREAD

**Issue by codemaster101gangster** [bluecreeper111/JEssentials#25]
Error occurred while enabling JEssentials v1.4.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/milkbowl/vault/economy/Economy
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:201) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.2.jar:git-Paper-58]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at com.bluecreeper111.jessentials.Main.onEnable(Main.java:134) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855) ~[patched_1.14.2.jar:git-Paper-58]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.economy.Economy
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.2.jar:git-Paper-58]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	... 19 more
[21:30:15] [Server thread/INFO]: [JEssentials] Disabling JEssentials v1.4.1
[21:30:15] [Server thread/ERROR]: Error occurred while disabling JEssentials v1.4.1 (Is it up to date?)
java.lang.NullPointerException: null
	at com.bluecreeper111.jessentials.Main.onDisable(Main.java:179) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:452) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.2.jar:git-Paper-58]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.2.jar:git-Paper-58]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855) ~[patched_1.14.2.jar:git-Paper-58]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by jeremy-carefoot** [comment]
You need to install the plugin Vault. This should solve your problem.
Head to our Discord for support next time ;) .
