### ISSUE TITLE
/sethome is raising an internal error

### ISSUE THREAD

**Issue by sambrashaw** [bluecreeper111/JEssentials#30]
When I run '/sethome home' in chat it says 'An internal error occurred while attempting to perform this command'.

The server output after running the command is:
```org.bukkit.command.CommandException: Unhandled exception executing command 'sethome' in plugin JEssentials v1.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1670) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
        at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPrimaryGroup(Permission_SuperPerms.java:96) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:679) ~[?:?]
        at net.milkbowl.vault.permission.Permission.getPrimaryGroup(Permission.java:691) ~[?:?]
        at com.bluecreeper111.jessentials.commands.SetHome.howManyHomes(SetHome.java:32) ~[?:?]
        at com.bluecreeper111.jessentials.commands.SetHome.onCommand(SetHome.java:58) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.2.jar:git-Spigot-baafee9-043d31d]
        ... 17 more```

**Comment by jeremy-carefoot** [comment]
I have taken notice to this bug and uploading a patch.
