### ISSUE TITLE
I'm getting an error trying to run the plugin. I'm not sure if 1.13 is the right version for that one

### ISSUE THREAD

**Issue by GorgeusFreeman** [bluecreeper111/JEssentials#4]
`[22:29:20 ERROR]: Error occurred while enabling JEssentials v1.3.3 (Is it up to date?)
java.lang.NullPointerException: null
at com.bluecreeper111.jessentials.Main.setupChat(Main.java:464) ~[?:?]
at com.bluecreeper111.jessentials.Main.onEnable(Main.java:131) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[craftbukkit.jar:git-Bukkit-1c7adf7]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:331) [craftbukkit.jar:git-Bukkit-1c7adf7]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [craftbukkit.jar:git-Bukkit-1c7adf7]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:411) [craftbukkit.jar:git-Bukkit-1c7adf7]
at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:337) [craftbukkit.jar:git-Bukkit-1c7adf7]
at net.minecraft.server.v1_13_R1.MinecraftServer.m(MinecraftServer.java:553) [craftbukkit.jar:git-Bukkit-1c7adf7]
at net.minecraft.server.v1_13_R1.MinecraftServer.g_(MinecraftServer.java:515) [craftbukkit.jar:git-Bukkit-1c7adf7]
at net.minecraft.server.v1_13_R1.MinecraftServer.a(MinecraftServer.java:414) [craftbukkit.jar:git-Bukkit-1c7adf7]
at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:264) [craftbukkit.jar:git-Bukkit-1c7adf7]
at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:664) [craftbukkit.jar:git-Bukkit-1c7adf7]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

**Comment by jeremy-carefoot** [comment]
Do you have the plugin **vault** installed? If not, this is an error that can be returned in the onEnable().

**Comment by GorgeusFreeman** [comment]
I installed vault before jEssentials. I could imagine the vault plugin would be the problem because it doesn't match with the current server version.

If anyone needs more information (log, plugin list) about the issue just let me know

**Comment by jeremy-carefoot** [comment]
Update your vault plugin to the latest version. It shouldn't affect anything because its just an api. That will probably solve your issue.

**Comment by ghost** [comment]
I get this same issue in the console as well. Everything is up to date with the latest available. Any help? Need any logs or files to check?

**Comment by jeremy-carefoot** [comment]
> I get this same issue in the console as well. Everything is up to date with the latest available. Any help? Need any logs or files to check?

Please send me the error you get.

**Comment by jeremy-carefoot** [comment]
After some testing I have found that this is a bug that occurs when you don't have a permissions plugin such as Pex or GroupManager installed. Working to fix this now.

**Comment by jeremy-carefoot** [comment]
Bug has been fixes in JEssentials V1.3.4
