### ISSUE TITLE
No lang file found! Please install one from our github

### ISSUE THREAD

**Issue by D1g1Byt3** [bluecreeper111/JEssentials#5]
[19:50:17] [Server thread/ERROR]: No lang file found! Please install one from our github.
[19:50:17] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'setspawn' in plugin JEssentials v1.3.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1620) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1460) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:356) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	at com.bluecreeper111.jessentials.api.api.translateColor(api.java:151) ~[?:?]
	at com.bluecreeper111.jessentials.api.api.getLangString(api.java:184) ~[?:?]
	at com.bluecreeper111.jessentials.commands.SetSpawn.onCommand(SetSpawn.java:43) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-f09662d-0e1cea5]
	... 15 more

lang.yml exists. But keeps getting created in the plugins "Root" folder and not plugins/JEssentials

Downloading and putting a lang.yml into JEssentials folder does nothing.
![plugins](https://user-images.githubusercontent.com/800872/56251702-1a001380-607a-11e9-9013-78022f1eaf42.png)

**Comment by jeremy-carefoot** [comment]
So the lang.yml file is being created inside of the plugins folder?

**Comment by D1g1Byt3** [comment]
Yeah and not the plugins/JEssentials like it should be.

**Comment by jeremy-carefoot** [comment]
Issue resolved in new update.
