### ISSUE TITLE
/BACK ERROR AND USERS CAN USE COLORS! IS NOT PERMISSIONS

### ISSUE THREAD

**Issue by TheFlamingOMG** [bluecreeper111/JEssentials#51]
[19:31:58] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'warp' in plugin JEssentials v1.5.9
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: Cannot translate null text
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at com.bluecreeper111.jessentials.api.api.translateColor(api.java:159) ~[?:?]
	at com.bluecreeper111.jessentials.api.api.getLangString(api.java:192) ~[?:?]
	at com.bluecreeper111.jessentials.api.api.tpDelayLoc(api.java:61) ~[?:?]
	at com.bluecreeper111.jessentials.commands.Warp.onCommand(Warp.java:127) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	... 17 more
[19:32:00] [Async Chat Thread - #1/INFO]: [0;33;1m[0;33;1mJuank_325[0;36;1m»[0;37;1mmm[m
[19:32:11] [Server thread/INFO]: YAMATOVY issued server command: /afk
[19:32:11] [Server thread/ERROR]: Error occured: Couldn't find message mailFull
[19:32:11] [Server thread/ERROR]: Could not pass event PlayerCommandPreprocessEvent to JEssentials v1.5.9
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1658) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: Cannot translate null text
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at com.bluecreeper111.jessentials.api.api.translateColor(api.java:159) ~[?:?]
	at com.bluecreeper111.jessentials.api.api.getLangString(api.java:192) ~[?:?]
	at com.bluecreeper111.jessentials.event.playerGive.onPlayerGive(playerGive.java:32) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	... 18 more
[19:32:11] [Server thread/ERROR]: Error occured: Couldn't find message afkBroadcast
[19:32:11] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'afk' in plugin JEssentials v1.5.9
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1666) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1506) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:872) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: Cannot translate null text
	at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	at com.bluecreeper111.jessentials.api.api.translateColor(api.java:159) ~[?:?]
	at com.bluecreeper111.jessentials.api.api.getLangString(api.java:192) ~[?:?]
	at com.bluecreeper111.jessentials.commands.Afk.onCommand(Afk.java:33) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.jar:git-Spigot-c8d4cef-1fee35b]
	... 17 more

**Comment by jeremy-carefoot** [comment]
It appears that all of these errors are because you are missing strings in your lang.yml file. Try deleting it and restarting your server, and make sure you are up to date.

**Comment by TheFlamingOMG** [comment]
anyways users can still use % and $ and prefix looks like server vanilla
<name>
