### ISSUE TITLE
Kit Issues Error Message

### ISSUE THREAD

**Issue by LucidAPs** [bluecreeper111/JEssentials#59]
[12:30:23 ERROR]: Error occured: Couldn't find message kitGive
[12:30:23 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'kitgive' in plugin JEssentials v1.5.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.14.3.jar:git-Paper-134]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.3.jar:git-Paper-134]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1837) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1645) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:1002) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:995) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:978) ~[patched_1.14.3.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:912) ~[patched_1.14.3.jar:git-Paper-134]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.IllegalArgumentException: Cannot translate null text
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[patched_1.14.3.jar:git-Paper-134]
        at org.bukkit.ChatColor.translateAlternateColorCodes(ChatColor.java:354) ~[patched_1.14.3.jar:git-Paper-134]
        at com.bluecreeper111.jessentials.api.api.translateColor(api.java:159) ~[?:?]
        at com.bluecreeper111.jessentials.api.api.getLangString(api.java:192) ~[?:?]
        at com.bluecreeper111.jessentials.commands.Kit.execute(Kit.java:295) ~[?:?]
        at com.bluecreeper111.jessentials.api.JCommand.onCommand(JCommand.java:73) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.14.3.jar:git-Paper-134]
        ... 17 more

**Comment by keepmcalive** [comment]
I also had this issue with kits on the newest installation, i reverted to the version I was using before and it resolved the kit issue, as a temp fix for the now.
